### ISSUE TITLE
Error with catmaid_get_connector_table()

### ISSUE THREAD

**Issue by alexanderbates** [jefferis/rcatmaid#65] opened 2016-10-03 13:30 UTC
When trying to run the demo code for this function:

`ct=catmaid_get_connector_table(10418394)
No encoding supplied: defaulting to UTF-8.
Error in FUN(X[[i]], ...) : subscript out of bounds`

**Comment by jefferis** [comment] 2016-10-03 14:13
larva or adult?

**Comment by alexanderbates** [comment] 2016-10-03 14:51
Larva

**Comment by alexanderbates** [comment] 2016-10-03 14:51
*Sorry, I realise that was an adult skid, but the error is the same with larval ones

**Comment by jefferis** [comment] 2016-10-08 08:50
So the problem is that the larval and adult servers are currently running incompatible versions of CATMAID. In particular the larval server is running a new version of CATMAID with an unannounced API change in the `/connector/table/list` endpoint.

There is a *additional* change on the dev branch (see https://github.com/catmaid/CATMAID/blob/dev/API_CHANGELOG.md) but I don't know what I'm supposed to do in the interim since. The larval and adult servers return the following version strings:

```
> catmaid_version(l1conn)
[1] "2016.09.01-68-gae543ac"

> catmaid_version(fafbconn)
[1] "2016.09.01-9-g059b97c"
```

I would have assumed that the last parts are some kind of short sha1 hash but I can't find anything matching those in the https://github.com/catmaid/CATMAID/ repo. In other words both servers a running something similar to the `2016.09.01` release, but clearly there is a difference.  So I'm a bit stuck because I can't even see how to test for a catmaid version string to made tailor the POST to the different API versions.

@tomka can you give any insight into these version differences and if there is a principled way to test them?

**Comment by tomka** [comment] 2016-10-09 06:41
I am currently traveling, so only briefly: the format is `LAST_RELEASE-N-gCOMMIT` where N is the number of commits applied after the last release. If you strip the "g" in the beginning of the last part, you get the actual commit. We use "git describe" to generate this version information.

**Comment by jefferis** [comment] 2016-10-09 07:15
Thanks a lot, @tomka. That's very helpful. 

So that commit is on the dev branch:

https://github.com/catmaid/CATMAID/commit/07a6ee2def439bb923121b4d85e60f730dbf364f

More generally if I am trying to keep an external tool up to date with the CATMAID API it is going to be very difficult unless API changes only happen with releases or I can assume linear history between releases. The first is clearly not happening. I am not sure about the second point. Is it reasonable to assume that CATMAID servers are running off a commit on the dev branch if they are not a release version?

Thanks,

Greg.

**Comment by tomka** [comment] 2016-10-10 13:31
Well, API changes happen in regular commits in the `dev` branch and we try to note all of them in the `API_CHANGELOG.md` file you referenced above. Ideally, production servers run only actual release versions (which then include API changes) of maintenance releases (that should not introduce API changes). Sometimes a release version has bugs that need to be addressed quickly. In this case we create a maintenance branch off of such a release and update the server to it. We currently don't tag these, but maybe we should so that his becomes clear from the displayed `git describe` version string. These maintenance branches are then merged into `dev` as well so that they become part of the next release, too.

The FAFB server should always follow this and currently is on a maintenance branch, which only adds small fixes on top of the last release (branch `maintenance/2016.09.01` in this case). The larval server doesn't always follow this principle and currently runs a regular `dev` branch commit. Albert sometimes updates the server to have a new feature quickly available without waiting for a new release.

So if a CATMAID server is not on a release version it can be on a maintenance version or a `dev` branch commit. There shouldn't be any other case. In case a `dev` branch commit is used, it is reasonable to expect it is newer than the last release, i.e. history is linear.

Does this make things clearer? Let me know if you need more details or if you have suggestions for improving this workflow to make things easier for you.

**Closed** 2016-10-14 15:56 UTC

**Comment by jefferis** [comment] 2016-10-14 17:00
So I have fixed this particular issue using code like:
```r
if(catmaid_version(numeric = TRUE)>="2016.09.01-65"){
  ## new style call
} else {
 ## old style call
}

I think this will nearly always work, but there could be pathological cases when changes are made on different branches and this kind of check fails.

**Comment by tomka** [comment] 2016-10-14 22:01
This should do for now. The adult fly server will be updated soon anyway.
