### ISSUE TITLE
fetch mesh from CATMAID

### ISSUE THREAD

**Issue by artxz** [jefferis/rcatmaid#133] opened 2019-07-31 21:12 UTC
`catmaid_get_volume() `gives an error when the argument is, instead of id, character name:

```
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 559, 638
```

Also the first example in the function's documentation, `v375=catmaid_get_volume(375)`, seems outdated (couldn't find matching volume with id = 375)

**Comment by jefferis** [comment] 2019-07-31 21:18
Hi @artxz 

* can you check what version of the catmaid package you have? You could paste the result of `devtools::session_info()`
* can you confirm the exact command that failed when you were requesting a volume by name rather than id?
* can you confirm which server you are using?
* I will fix the example – using numeric ids is not a great Idea because they can indeed change.

**Comment by artxz** [comment] 2019-07-31 21:28
- Session info ----------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2019-07-31                  

- Packages --------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package            * version    date       lib source                                         
 abind                1.4-5      2016-07-21 [1] CRAN (R 3.4.1)                                 
 alphahull          * 2.1        2016-02-15 [1] CRAN (R 3.4.4)                                 
 alphashape3d       * 1.3        2017-12-21 [1] CRAN (R 3.4.3)                                 
 assertthat           0.2.1      2019-03-21 [1] CRAN (R 3.4.4)                                 
 backports            1.1.4      2019-04-10 [1] CRAN (R 3.4.4)                                 
 callr                3.2.0      2019-03-15 [1] CRAN (R 3.4.4)                                 
 catmaid            * 0.9.8      2019-04-26 [1] Github (jefferis/rcatmaid@a720f81)             
 checkmate            1.9.1      2019-01-15 [1] CRAN (R 3.4.4)                                 
 cli                  1.1.0      2019-03-19 [1] CRAN (R 3.4.4)                                 
 codetools            0.2-15     2016-10-05 [2] CRAN (R 3.4.2)                                 
 colorspace           1.4-1      2019-03-18 [1] CRAN (R 3.4.4)                                 
 crayon               1.3.4      2017-09-16 [1] CRAN (R 3.4.3)                                 
 crosstalk            1.0.0      2016-12-21 [1] CRAN (R 3.4.3)                                 
 curl                 3.3        2019-01-10 [1] CRAN (R 3.4.4)                                 
 deldir               0.1-15     2018-04-01 [1] CRAN (R 3.4.4)                                 
 dendroextras         0.2.3      2018-01-25 [1] CRAN (R 3.4.4)                                 
 desc                 1.2.0      2018-05-01 [1] CRAN (R 3.4.4)                                 
 devtools             2.0.2      2019-04-08 [1] CRAN (R 3.4.4)                                 
 digest               0.6.18     2018-10-10 [1] CRAN (R 3.4.4)                                 
 dotCall64            1.0-0      2018-07-30 [1] CRAN (R 3.4.4)                                 
 dplyr                0.8.0.1    2019-02-15 [1] CRAN (R 3.4.4)                                 
 elmr               * 0.5.5.9000 2019-04-26 [1] Github (jefferis/elmr@e34dc5e)                 
 evaluate             0.13       2019-02-12 [1] CRAN (R 3.4.4)                                 
 filehash             2.4-2      2019-04-17 [1] CRAN (R 3.4.4)                                 
 fs                   1.2.7      2019-03-19 [1] CRAN (R 3.4.4)                                 
 geometry           * 0.4.1      2019-03-27 [1] CRAN (R 3.4.4)                                 
 ggplot2              3.1.1      2019-04-07 [1] CRAN (R 3.4.4)                                 
 glue                 1.3.1      2019-03-12 [1] CRAN (R 3.4.4)                                 
 goftest              1.1-1      2017-04-03 [1] CRAN (R 3.4.1)                                 
 gtable               0.3.0      2019-03-25 [1] CRAN (R 3.4.4)                                 
 htmltools            0.3.6      2017-04-28 [1] CRAN (R 3.4.2)                                 
 htmlwidgets        * 1.3        2018-09-30 [1] CRAN (R 3.4.4)                                 
 httpuv               1.5.1      2019-04-05 [1] CRAN (R 3.4.4)                                 
 httr               * 1.4.0      2018-12-11 [1] CRAN (R 3.4.4)                                 
 igraph             * 1.2.4.1    2019-04-22 [1] CRAN (R 3.4.4)                                 
 jsonlite             1.6        2018-12-07 [1] CRAN (R 3.4.4)                                 
 knitr              * 1.22       2019-03-08 [1] CRAN (R 3.4.4)                                 
 later                0.8.0      2019-02-11 [1] CRAN (R 3.4.4)                                 
 lattice              0.20-35    2017-03-25 [2] CRAN (R 3.4.2)                                 
 lazyeval             0.2.2      2019-03-15 [1] CRAN (R 3.4.4)                                 
 magic                1.5-9      2018-09-17 [1] CRAN (R 3.4.4)                                 
 magrittr             1.5        2014-11-22 [1] CRAN (R 3.4.2)                                 
 manipulateWidget     0.10.0     2018-06-11 [1] CRAN (R 3.4.4)                                 
 Matrix               1.2-11     2017-08-21 [2] CRAN (R 3.4.2)                                 
 memoise              1.1.0      2017-04-21 [1] CRAN (R 3.4.2)                                 
 mgcv                 1.8-20     2017-09-14 [2] CRAN (R 3.4.2)                                 
 mime                 0.6        2018-10-05 [1] CRAN (R 3.4.4)                                 
 miniUI               0.1.1.1    2018-05-18 [1] CRAN (R 3.4.4)                                 
 munsell              0.5.0      2018-06-12 [1] CRAN (R 3.4.4)                                 
 nabor                0.5.0      2018-07-11 [1] CRAN (R 3.4.4)                                 
 nat                * 1.9.0      2019-04-26 [1] Github (jefferis/nat@4ff3508)                  
 nat.flybrains      * 1.7.3      2019-06-03 [1] Github (jefferislab/nat.flybrains@6cbc507)     
 nat.nblast         * 1.6.2      2016-04-26 [1] CRAN (R 3.4.4)                                 
 nat.templatebrains * 0.9        2019-06-03 [1] Github (jefferislab/nat.templatebrains@e0cb692)
 nat.utils            0.5.1      2015-07-04 [1] CRAN (R 3.4.2)                                 
 nlme                 3.1-131    2017-02-06 [2] CRAN (R 3.4.2)                                 
 pillar               1.3.1      2018-12-15 [1] CRAN (R 3.4.4)                                 
 pkgbuild             1.0.3      2019-03-20 [1] CRAN (R 3.4.4)                                 
 pkgconfig            2.0.2      2018-08-16 [1] CRAN (R 3.4.4)                                 
 pkgload              1.0.2      2018-10-29 [1] CRAN (R 3.4.4)                                 
 plyr                 1.8.4      2016-06-08 [1] CRAN (R 3.4.2)                                 
 polyclip             1.6-1      2017-03-22 [1] CRAN (R 3.4.1)                                 
 prettyunits          1.0.2      2015-07-13 [1] CRAN (R 3.4.4)                                 
 processx             3.3.0      2019-03-10 [1] CRAN (R 3.4.4)                                 
 promises             1.0.1      2018-04-13 [1] CRAN (R 3.4.4)                                 
 ps                   1.3.0      2018-12-21 [1] CRAN (R 3.4.4)                                 
 purrr                0.3.2      2019-03-15 [1] CRAN (R 3.4.4)                                 
 R.methodsS3          1.7.1      2016-02-16 [1] CRAN (R 3.4.1)                                 
 R.oo                 1.21.0     2016-11-01 [1] CRAN (R 3.4.1)                                 
 R.utils              2.6.0      2017-11-05 [1] CRAN (R 3.4.4)                                 
 R6                   2.4.0      2019-02-14 [1] CRAN (R 3.4.4)                                 
 rappdirs             0.3.1      2016-03-28 [1] CRAN (R 3.4.3)                                 
 Rcpp                 1.0.1      2019-03-17 [1] CRAN (R 3.4.4)                                 
 remotes              2.0.4      2019-04-10 [1] CRAN (R 3.4.4)                                 
 rgl                * 0.100.19   2019-03-12 [1] CRAN (R 3.4.4)                                 
 rjson              * 0.2.15     2014-11-03 [1] CRAN (R 3.4.1)                                 
 rlang                0.3.4      2019-04-07 [1] CRAN (R 3.4.4)                                 
 rmarkdown          * 1.8        2017-11-17 [1] CRAN (R 3.4.3)                                 
 rpart                4.1-11     2017-03-13 [2] CRAN (R 3.4.2)                                 
 rprojroot            1.3-2      2018-01-03 [1] CRAN (R 3.4.3)                                 
 rstudioapi           0.7        2017-09-07 [1] CRAN (R 3.4.2)                                 
 scales               1.0.0      2018-08-09 [1] CRAN (R 3.4.4)                                 
 sessioninfo          1.1.1      2018-11-05 [1] CRAN (R 3.4.4)                                 
 sgeostat             1.0-27     2016-02-03 [1] CRAN (R 3.4.1)                                 
 shiny                1.3.2      2019-04-22 [1] CRAN (R 3.4.4)                                 
 sp                   1.3-1      2018-06-05 [1] CRAN (R 3.4.4)                                 
 spam                 2.2-2      2019-03-08 [1] CRAN (R 3.4.4)                                 
 spatstat             1.55-0     2018-01-29 [1] CRAN (R 3.4.4)                                 
 spatstat.data        1.2-0      2017-11-20 [1] CRAN (R 3.4.4)                                 
 spatstat.utils       1.8-0      2017-11-20 [1] CRAN (R 3.4.4)                                 
 splancs              2.01-40    2017-04-16 [1] CRAN (R 3.4.4)                                 
 tensor               1.5        2012-05-05 [1] CRAN (R 3.4.1)                                 
 testthat             2.0.0      2017-12-13 [1] CRAN (R 3.4.3)                                 
 tibble               2.1.1      2019-03-16 [1] CRAN (R 3.4.4)                                 
 tidyselect           0.2.5      2018-10-11 [1] CRAN (R 3.4.4)                                 
 tripack              1.3-8      2016-12-16 [1] CRAN (R 3.4.1)                                 
 usethis              1.5.0      2019-04-07 [1] CRAN (R 3.4.4)                                 
 webshot              0.5.1      2018-09-28 [1] CRAN (R 3.4.4)                                 
 withr                2.1.2      2018-03-15 [1] CRAN (R 3.4.4)                                 
 xfun                 0.6        2019-04-02 [1] CRAN (R 3.4.4)                                 
 xml2                 1.2.0      2018-01-24 [1] CRAN (R 3.4.4)                                 
 xtable               1.8-4      2019-04-21 [1] CRAN (R 3.4.4)                                 
 yaml                 2.2.0      2018-07-25 [1] CRAN (R 3.4.4)   
------------------------------------------------------------------

This fails with the error in the first post
`catmaid_get_volume("v14.neuropil")`

------------------------------------------------------------------
catmaid.server="https://neuropil.janelia.org/tracing/fafb/v14"

**Comment by jefferis** [comment] 2019-07-31 21:34
Thanks. There is an updated version, so I recommend installing that as usual. I note that your version of R is starting to get old (3.4.2) but I don't know of a reason why that should be a problem.

Can you give me the result of `traceback()` because I cannot reproduce your error with `catmaid_get_volume("v14.neuropil")` (It works perfectly for me).

Finally with the latest version of the package

```
> v375=catmaid_get_volume(375)
 Error: catmaid_get_volume of type: ValueError
  Could not find volume 375 
```
already gives a better error.

**Comment by artxz** [comment] 2019-07-31 21:51
Thanks @jefferis  !

The traceback() result is very long, more the 1000 lines. I think i'll try updating the packages. If the error persists i'll somehow send the traceback() result.

**Comment by jefferis** [comment] 2019-07-31 21:51
OK. You can attach the traceback as a text file by drag and drop.

**Comment by jefferis** [comment] 2019-08-10 16:10
I'm closing this because it seems to have been fixed by an upgrade.

**Closed by jefferis** 2019-08-10 16:10 UTC
